/************************************************************************************
 * 1 - Objetivo: responsavel pela manipulação dos alunos no banco de dados
 * 2 - Data: 14/4/2023
 * 3 - Autor: Oswaldo Barbosa
 * 4 - Versão: 1.0
 ************************************************************************************
 */

//inserir dados do aluno no banco de dados
const selectAllAluno = () => {

}

//retorna dados do aluno no banco de dados pelo id
const selectByIdAluno = (id) => {

}

//inserir dados do aluno no banco de dados
const insertAluno = () => {

}

//atualizar dados do aluno no banco de dados
const updateAluno = () => {

}

//deletar dados do aluno no banco de dados
const deleteAluno = (id) => {

}